name: CI-build2
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    name: build&deploy
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
#       with:
#         persist-credentials: false

    - name: Use Node.js 12.8
      uses: actions/setup-node@v1
      with:
        node-version: 12.8  

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build -- --prod
      
    - name: List output files
      run: ls
    
    - name: Upload ftp
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: 91.219.122.5
        user: kubamiszcz-ftp
        password: ${{ secrets.FTP_PASSWORD }}
        localDir: "dist/KMDevTools"
        remoteDir: "kmdevtools.hostingasp.pl/wwwroot/my"
#         forceSsl: false
       
